name: ci-golang-demo-matyushkin

on:
    push:
      branches:
        - main

jobs:
    my_setup:
        runs-on: ubuntu-latest

        steps:
            - name: Git clone my repo
              uses: actions/checkout@v4

            - name: Set up Go
              uses: actions/setup-go@v4
              with:
                go-version: '1.12'

    my_test:
        runs-on: ubuntu-latest
        needs: [my_setup]
        
        steps:
            - name: test_make_lint
              run: make lint

             - name: test_make_test
               run: make test