name: Go package

on:
    push:
      branches:
        - main

jobs:
    job debug:
        runs-on: ubuntu-latest

        steps:
            - name: Git clone my repo
              uses: actions/checkout@v4

            - name: List current folder
            run : ls -la