name: ci-golang-demo-matyushkin

on:
    push:
      branches:
        - main

jobs:
    my_setup:
        runs-on: ubuntu-latest

        steps:
            - name: Git clone my repo
              uses: actions/checkout@v4

            - name: Set up Go
              uses: actions/setup-go@v4
              with:
                go-version: '1.20'

            - name: instal go lint
              run: go get -u golang.org/x/lint/golint

            - name: test_make_lint
              run: make lint
            
            - name: test_make_test
              run: make test